### ISSUE TITLE
TypeError: PiNetwork is not a constructor

### ISSUE THREAD

**Issue by bailaoshijiadao** [pi-apps/pi-nodejs#9]
file:///D:/github/2345pi-app-nav/server.js:23const 
pi = new PiNetwork(apiKey, walletPrivateSeed)
TypeError: PiNetwork is not a constructorat 
file:///D:/github/2345pi-app-nav/server.js:23:12at 
ModuleTob.run (node:internal/modules/esm/module job:194:25)

Is this step an error due to my environment?

The environment of this project
https://github.com/pi-apps/2345pi-app-nav

**Comment by Chidiebere95** [comment]
I think it's because pi-backend (for nodejs) is not fully supported yet. You can try running it on ruby

**Comment by xsuve** [comment]
I don't think we should use it like this, but I was able to do something like this (until it gets fixed):
```js
import PiNetwork from "pi-backend";

const pi = new PiNetwork.default(
    process.env.PI_API_KEY,
    process.env.PI_WALLET_SEED
);
```

Note that I used the `.default()` function/constructor of the entire `PiNetwork` object to construct the `pi` object.
Then the `pi` object can be used normally to call the other methods:

```js
const paymentId = await pi.createPayment({ ... });
...
```

**Comment by JustUsKriogen** [comment]
Can anyone explain properly how to use this with node?

This is my setup:
const PiNetwork = require("pi-backend").default;

const networkPassphrase = process.env.NETWORK_PASSPHRASE || "Pi Network"; // Default to mainnet if not set
                const axiosOptions = {
                    headers: {
                        Authorization: `Key ${process.env.PI_API_KEY}`,
                    },
                    timeout: 15000,
                    networkPassphrase: networkPassphrase,
                };

                console.log(networkPassphrase);

                // Initialize Pi SDK with positional arguments and Axios options
                const apiKey = process.env.PI_API_KEY;
                const privateSeed = process.env.PI_PRIVATE_SEED;
                console.log(`[${timestamp}] 🔍 Initializing PiNetwork with API Key: ${apiKey ? "Set" : "Not Set"}, Private Seed: ${privateSeed ? "Set" : "Not Set"}`);
                const pi = new PiNetwork(apiKey, privateSeed, axiosOptions);

And i get 401...
❌ Failed to process refund for booking 19: {
  message: 'Request failed with status code 401',
  stack: 'AxiosError: Request failed with status code 401\n' +
    '    at settle (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:2031:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:3148:11)\n' +
    '    at IncomingMessage.emit (node:events:536:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1698:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n' +
    '    at Axios.request (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:4258:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)'
}

**Comment by MCKmecik** [comment]
> Can anyone explain properly how to use this with node?
> 
> This is my setup: const PiNetwork = require("pi-backend").default;
> 
> const networkPassphrase = process.env.NETWORK_PASSPHRASE || "Pi Network"; // Default to mainnet if not set const axiosOptions = { headers: { Authorization: `Key ${process.env.PI_API_KEY}`, }, timeout: 15000, networkPassphrase: networkPassphrase, };
> 
> ```
>             console.log(networkPassphrase);
> 
>             // Initialize Pi SDK with positional arguments and Axios options
>             const apiKey = process.env.PI_API_KEY;
>             const privateSeed = process.env.PI_PRIVATE_SEED;
>             console.log(`[${timestamp}] 🔍 Initializing PiNetwork with API Key: ${apiKey ? "Set" : "Not Set"}, Private Seed: ${privateSeed ? "Set" : "Not Set"}`);
>             const pi = new PiNetwork(apiKey, privateSeed, axiosOptions);
> ```
> 
> And i get 401... ❌ Failed to process refund for booking 19: { message: 'Request failed with status code 401', stack: 'AxiosError: Request failed with status code 401\n' + ' at settle (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:2031:12)\n' + ' at IncomingMessage.handleStreamEnd (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:3148:11)\n' + ' at IncomingMessage.emit (node:events:536:35)\n' + ' at endReadableNT (node:internal/streams/readable:1698:12)\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n' + ' at Axios.request (/opt/render/project/src/node_modules/axios/dist/node/axios.cjs:4258:41)\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:105:5)' }

Hi @JustUsKriogen, have you resolved this problem? We have the exact same error code when creating a payment and we are stuck on this.

Thanks.

**Comment by philipeachille** [comment]
instead of

`import PiNetwork from "pi-backend";`

i use

```
async function getPiNetworkClass() {
  const module = await import('pi-backend');
  return module.default.default;
}

const PiNetworkClass = await getPiNetworkClass();
const pi = new PiNetworkClass(YOUR_PI_AUTH_KEY, YOUR_PI_WALLET_PRIVATE_SEED);

```
